### ISSUE TITLE
SCR Calculation Incorrect

### ISSUE THREAD

**Issue by ajakubiec** [chriswmackey/Dragonfly#16]
Hi Chris,

See the referenced line of code, https://github.com/chriswmackey/Dragonfly/blob/3ab5f7553987a1da31622ad88cb2b6ebca716f4d/src/Dragonfly_UWG%20City%20from%20Typologies.py#L378

This is incorrect, because totalGrassCoverage is the ratio of the grass area to the (grass area + paved area). Total terrain area should be totalBuiltArea + totalPavedArea + totalGrass**Area**.

Separately, I think there are some other funky area things going on in your script, (like that you presume buildings have pavement underneath them in the model). 

Best,
Alstan

**Comment by chriswmackey** [comment]
Hi Alstan,
Sorry for the late response.  My attention fell by the wayside now that @saeranv has finished translating the U[rban Weather Generator to Python](https://github.com/ladybug-tools/urbanWeatherGen) and we can finally fix some bugs/uncaught exceptions that were deep within the Matlab code.

The way that I wrote this component was that I expected people to plug in non-overlapping breps for grass area and paved areas.  So (correct me if I am wrong), this calculation should be correct as long as there is no overlap between the grass and paved surfaces.  In this case, I think the funkiness you describe should become clearer with this understanding.  

If I am interpreting the situation correctly, are you saying that its conceptually cleaner to plug in a single surface that represents the entire terrain and then put co-planar surfaces representing grass on top of this? (somewhat like EnergyPlus glazing that are children of a parent opaque surface)?

-Chris

**Comment by ajakubiec** [comment]
Hi Chris,

Likewise I apologize for a late response--I'm traveling about the US right now. 

Anyways, I think there is 1 issue/bug here and 1 criticism that I had. Let me try to be explicit (I should have made two threads). 

**Issue / bug**
Your code defines totalGrassCoverage as the below, so it is a ratio between the grass area and the total unbuilt area. 
`totalGrassCoverage = totalGrassArea/(totalPavedArea+totalGrassArea)`

But then you calculate the total site area as the below. It doesn't make sense to add in the ratio (totalGrassCoverage). Instead totalGrassArea should be added, I believe. 
`totalTerrainArea = totalBuiltArea + totalPavedArea + totalGrassCoverage`

**Concern**
Consider an urban model with streets (paved area), ground surfaces that are planted (grass area), and buildings (built area). What surprised me is that its not clear that there should be paved areas underneath each building. Somehow there could be extra clarity in the modeling expectations. See line 346 which is the below. Basically the built area is always subtracted from the ground areas to get the total paved area. At least usually I don't model in this way where there is some surface underneath the buildings. 
`totalPavedArea = sum(groundAreas) - totalBuiltArea`

**Comment by chriswmackey** [comment]
@ajakubiec ,
Yes, that's a bug.  Thank you very much for finding it.  I just fixed it here:
https://github.com/chriswmackey/Dragonfly/commit/7eab4cefe7dfaffc72d12c10d3e4e3cef4f863d2
If you sync with the github, you'll have the fixed version and I'll try to update the example file soon.

As for the concern, I realize that the current setup is a bit confusing.  I should either make the pavementBrep only representative of the pavement (not the area beneath the building or the grass).  Or I own the idea that that we want to put in one brep for all of the terrain and I call it something else like terrainBrep instead of pavementBrep (in this case the grass surfaces should be co-planar to the terrainBrep and the terrainBrep can include the area beneath the buildings).

I'll leave this issue open until I can address this and let me know if you are leaning a particular side of this decision.  Personally, I like the second solution with the terrainBrep because I can still easily deal with cases where we have portions of the building geometry cantilevering over the pavement.  In other words, I won't expect you to punch out of the pavement brep that is underneath the cantilever.

Let me know if you agree or if you have an argument to the contrary.
And thanks again!

**Comment by saeranv** [comment]
@chriswmackey, @ajakubiec  

If I'm following along correctly, I'd like to add that from a modeling perspective I believe option two (using terrainBrep as an universal underlying surface that overlaps building and vegetated footprints) would be much easier. If there is a need to keep each set of surfaces discrete (no overlaps), then users would have to choose between using time-consuming manual methods in Rhino, or Grasshopper's unreliable solid/curve boolean methods. 

I definitely agree that clarifying this in the component documentation would be helpful. 

S

**Comment by chriswmackey** [comment]
I just wanted to add that I am addressing this in the new revision of Dragonfly that I am working on right now. The new version that will use the python UWG will involve inputting a brep for the whole terrain and grass areas should be coplanar with this terrain surface.

**Comment by chriswmackey** [comment]
@ajakubiec ,
I just wanted to let you know that we have a working version of the new Dragonfly and you can download the sample file here:
https://github.com/chriswmackey/Dragonfly/tree/master/newPlugin/sampleFiles

This new version is working with the [Python UWG](https://github.com/ladybug-tools/urbanWeatherGen) and I'll get some detailed installation instructions up here soon.
You will see that the new version of Dragonfly is a lot cleaner and it addresses the SCR concern that you brought up here.  It also does a much more accurate job with a lot of other parameters.  For example, when you connect up multiple building typologies, it will calculate a glazing ratio for the "infinite urban canyon" that is weighted by the facade area of the typologies (instead of the total floor area)
As such, I am going to close out the issue for now and I'll start transitioning all of the resources over to the new version.
