### ISSUE TITLE
Overwrite the Envelope Properties of Individual Typologies in the UWG Exporter

### ISSUE THREAD

**Issue by chriswmackey** [chriswmackey/Dragonfly#30]
I think I will add some code in the Dragonfly "Run WUG" component that automatically overwrites the glazing ratio of each typology after init_input_obj() is run. This way, it will use the facade-area-weighted glazing ratio across all typologies in the "infinite urban canyon" calculation but it will use the glazing ratio of each individual typology when running the BEM for each typology. 

See more info here:
https://github.com/ladybug-tools/urbanWeatherGen/issues/18#issuecomment-392309705

**Comment by saeranv** [comment]
@chriswmackey 

I think this is the right way to do it. As I mentioned in briefly in the UWG issue you referenced, I decided to overwrite all the building typology parameters with the one optional SHGC/albedo etc parameters because trying to capture typology-specific optional building parameters would mean we'd have to do something like this for every building type:

```
# WWR for each DOE Building type (pre-80's build, 80's-present build, new)
0,0,0,    # FullServiceRestaurant
0,0,0,    # Hospital
0,0,0,    # LargeHotel
0,0.4,0,  # LargeOffice
0,0,0,    # MediumOffice
0,0.6,0,  # MidRiseApartment
0,0,0,    # OutPatient
0,0,0,    # PrimarySchool
0,0,0,    # QuickServiceRestaurant
0,0,0,    # SecondarySchool
0,0,0,    # SmallHotel
0,0,0,    # SmallOffice
0,0,0,    # Stand-aloneRetail
0,0,0,    # StripMall
0,0,0,    # SuperMarket
0,0,0,    # Warehouse
```

Which I thought would be getting too complicated for the initialize.uwg method, especially as we've already discussed a lot of potential future customization of parameters. 

I propose we think of the initialize.uwg method as something that should be used for quick, simple, generic models. As we start increasing the customization of our building typologies using Dragonfly, it makes sense to handle this customization by directly using the API (as you are suggesting), and piggy-back on better UI components like Grasshopper componenters, rather then try and force it with the .uwg method, which is too limited to really do more customization. 

In terms of the code, I think you can customize the BEM objects after the init_input_obj() method for now. Although, it may be better coding practice to break out the the initialization of these objects into separate functions, (i.e create an init_BEM_obj method() ) so that we can isolate and customize the BEM object immediately.

**Comment by chriswmackey** [comment]
This has been addressed via https://github.com/chriswmackey/Dragonfly/commit/d33376c7010c6c97235757eb975576c1585c83e3

I am over-writing the individual parameters of each building typology here:
https://github.com/chriswmackey/Dragonfly/commit/d33376c7010c6c97235757eb975576c1585c83e3#diff-95fc5eb56942581a02377d2b1ce57eb7R189

@saeranv ,
I agree that building matrices for these parameters in the .uwg files seems too complex and we're much better off leaving this as a special thing that Dragonfly and python scripts do.

I think we should only create a separate method to edit the UWG typologies only after we have gotten a sense of everything that we want to expose in Dragonfly.
