### ISSUE TITLE
Change the simTime.dt to 200 seconds by default

### ISSUE THREAD

**Issue by saeranv** [chriswmackey/Dragonfly#47]
@chriswmackey 

As mentioned by Joseph, changing the default simTime.dt to 200 seconds will fix the FATAL ERROR mistake (at least for the version of this we've encountered thus far on the forums). 

I've changed the default to 200 seconds (in the initialize.uwg) in the UWG, and I think it would be a good idea to do the same thing for the DF components. 

Also, I've revised the error handling on the simTime and uwg.building code so that if users run into the FATAL ERROR, they are instructed to try and reduce the timestep, and the code catches any incorrect timestep inputs (i.e should be a factor of 3600, or else the timestep won't divide evenly per hour).

I'm just waiting for some instructions on how to commit my changes with correct semantic versioning and I'll add the new UWG code to this repo as well.

**Comment by saeranv** [comment]
Update: the refactored UWG code is available in this PR: https://github.com/chriswmackey/Dragonfly/pull/48

**Comment by chriswmackey** [comment]
Thanks for taking care of this @saeranv ,

As you can see, there is no versioning set up on the legacy repo here (my development of this repo is pretty much frozen).  The purpose of this repo at this point is mostly to help us find issues like this one so that we can make sure that they are fixed on the Dragonfly core library.

... and speaking of this, I have changed the default simTimestep on the Dragonfly core to now be 200:
https://github.com/ladybug-tools/dragonfly/commit/8b0e0e48622ebfe86a0d45e5de8be51570521770

Thanks again for solving this one!
