### ISSUE TITLE
Updated download links in Dragonfly_Dragonfly for latest UWG (v4.1)

### ISSUE THREAD

**Issue by saeranv** [chriswmackey/Dragonfly#6]
Hey @chriswmackey,

I was testing out the example file for the UWG from Hydra, and found that the Dragonfly_Dragonfly component isn't running due to outdated links to the UWG_Matlab repo. I forked the repo and changed the links/made a new userobject, and it's loading correctly now.

Here's the changes to the source file:
https://github.com/saeranv/Dragonfly/commit/bd0d13f8543244f9714decb0e34d222fd6079b04 

Edits:
1. Updated the updatedLink path to current repo.

2. Updated the UWG download link, and commented out the unzip function as the file from the repo is no longer a zip.

3. Updated the error message for not finding MRC 9.0 to reflect current requirements for R2015b version. I can't find any installer for MRC in the new repo, so I changed the message to direct users to "http://www.mathworks.com/products/compiler/mcr/index.html" . This is the process I ended up following. However in the UWG installer: https://github.com/hansukyang/UWG_Matlab/tree/master/UWGv4.1/for_redistribution there is an option (I think) to download the MCR, so we can also change the message to reflect that. What do you think?

If these changes looks good I'll send a pull request. 

S

**Comment by saeranv** [comment]
And... ten seconds after posting this, I just realized I forgot to use the Update Dragonfly component. Nevermind - rookie mistake. I'll close this.

**Comment by chriswmackey** [comment]
@saeranv ,
Thanks for going through this process. This has made me realize that I really need to update the hydra example and I will do this soon.  Within the next couple of months, the new components should also be usable.

**Comment by saeranv** [comment]
@chriswmackey 

I'm very excited by this project. Being able to take into account the urban environment in simulations would be really, really useful to me. I'm hoping to use this on a built form policy project I'm working on right now in Toronto  - http://www1.toronto.ca/wps/portal/contentonly?vgnextoid=222101f2e9745410VgnVCM10000071d60f89RCRD . 

What will the next update look like? i.e. are you planning on building more components or revising the existing ones?

**Comment by chriswmackey** [comment]
@saeranv ,

Glad to hear the excitement!  This type of application is definitely one that Dragonfly and the UWG can weigh in on, although the high latitude of Toronto means that there's probably more benefit to intensifying the heat island to mitigate the cold rather than diminishing it.  I should also give a general disclaimer that many people start using the UWG expecting the effect of heat island to be big but, in reality, it's not much larger than 0.5 C on average.  In other words, it is MUCH smaller than the effect that climate change will be having in the course of our lifetimes.

The revised components for the UWG are not going to add too many new capabilities as much as streamline the process, highlight the most relevant inputs, and make it easier to build off the work.  The person maintaining the UWG and I have both agreed that there are a lot of variables in the current input XML format that do not influence the UHI effect and that only serve as an opportunity to create bugs.  Furthermore, there are some very important parameters (like the traffic schedule) that are not really exposed.

I'm going to get to the new components once we push out the next stable release of LB+HB.

**Comment by chriswmackey** [comment]
@saeranv ,
I have updated the example file on Hydra so that this confusion hopefully will not happen again:
https://github.com/chriswmackey/hydra_2/commit/88dafb045922e4855949a1aeb7060b283b9ee651

-Chris
