### ISSUE TITLE
DF envimet: apply user custom materials

### ISSUE THREAD

**Issue by frank984** [chriswmackey/Dragonfly#73]
Maybe @AntonelloDN could find a solution to this issue:
I defined new wall in the envimet database manager (ENVi v. 4.4.5) :
![image](https://user-images.githubusercontent.com/6491927/84011386-51183f00-a976-11ea-80c9-bc4c729bf678.png)
Then I opened my .gh file and applied this wall to breps:
![image](https://user-images.githubusercontent.com/6491927/84011536-8e7ccc80-a976-11ea-9ba2-b9b505f08131.png)
I generated the .INX file:
![image](https://user-images.githubusercontent.com/6491927/84011721-d1d73b00-a976-11ea-82ea-2e0a5abaea3e.png)
Opened in ENVI spaces but all the three buildings have the base material applied to the walls:
![image](https://user-images.githubusercontent.com/6491927/84012683-38a92400-a978-11ea-8d36-479d242f50ec.png)
In this case, I have to apply the customed material from spaces by selecting all single building:
And then save the modified file.
![image](https://user-images.githubusercontent.com/6491927/84013038-b10fe500-a978-11ea-91e9-b834489dd508.png)
What's that depend on?

**Comment by AntonelloDN** [comment]
Hi @frank984,

Material shoud be there, could you try to repeat workflow and open directly 3D view, check if you see your custom material (try to give a color different from 000000 to your materials).
Please, let me know if you see your custom material on 3D view.

The issue should be only with 2D mode because of a small change in INX structure, if I am not wrong, with Monde integration. I can fix this small issue easily.
It should not be effect your simulation because df envimet components write only "Detailed 3D models".
Detail 3D models contain a 3D part with information of each building cell - that Envimet call facade. 2D part is partially ignored during calculation when Facades are in.
Anyway, thanks for this and I try to fix this night.

Best,
Antonello

**Comment by frank984** [comment]
> Please, let me know if you see your custom material on 3D view

Hi Antonello. First of all thank you for yout prompt reply.
I changed the colour of the wall:
![image](https://user-images.githubusercontent.com/6491927/84059791-724f4e80-a9bb-11ea-8283-48faec9e8900.png)
And effectively, in 3D view I can see my custom material:
![image](https://user-images.githubusercontent.com/6491927/84060047-d540e580-a9bb-11ea-9cfd-be3decadbf4c.png)
Thank you and have a good evening!
F.

**Comment by AntonelloDN** [comment]
@frank984 I have fixed it. I have released it in "stage environment" where envimet components code is: [df_envimet](https://github.com/AntonelloDN/df_envimet/blob/master/plugin%20beta/readme.md).
Feel you free to test it. Thanks.

**Comment by frank984** [comment]
I confirm that the issue has been resolved:
![image](https://user-images.githubusercontent.com/6491927/84151455-b1d17580-aa63-11ea-809e-796d0055daba.png)
Thank you @AntonelloDN!
